blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/chakra-ui/ark/discussions
    about: Ask questions and discuss topics with other community members
